GRANT ALL PRIVILEGES ON *.* TO 'bimuser'@'%'  IDENTIFIED BY 'test' WITH GRANT OPTION;

-- default values fail without this
SET GLOBAL sql_mode='ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
