
version: '3.5'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ../:/app:cached
            - cache:/app/var/cache
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php

    php:
        build:
            context: ./
            dockerfile: ./dockerfiles/Dockerfile-php-fpm
        ports:
            - "2222:22"
        volumes:
            - ../:/app:cached
            - cache:/app/var/cache
            - ./post-init-setup.sql:/app/post-init-setup.sql
            - ../fpm_custom.conf:/usr/local/etc/php-fpm.d/fpm_custom.conf
        links:
            - db
            - redis
        environment:
            XDEBUG_CONFIG: "idekey=${XDEBUG_IDEKEY:-VSCODE} remote_host=${XDEBUG_REMOTE_HOST:-docker.for.mac.localhost}"

    db:
        image: "mariadb:10.3.23"
        restart: always
        volumes:
            - ./dbdata:/var/lib/mysql
            - ./db.cnf:/etc/mysql/conf.d/db.cnf
            #- ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
            - ./backup:/backup
        ports:
            - "13306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_DATABASE=bimcontact
            - MYSQL_USER=bimuser
            - MYSQL_PASSWORD=test
        #command: mysql --user=root --password=test --execute="set GLOBAL sql_mode='ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';"
          # - MYSQL_ROOT_HOST='%'

    redis:
        image: redis
        restart: always

    realtime:
        build:
            context: ../external/ic-airborne-realtime-api
            dockerfile: ./Dockerfile
        links:
            - redis
        ports:
            - "8081:8080"
        environment:
            - REDIS_URL=redis://redis:6379/0
volumes:
  cache:



